spring.application.name=backend

server.port=8081

spring.datasource.url=jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.jvttkjxuauqwhvugtibe
spring.datasource.password=xbrjI77DgyiT61VE
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true